### ISSUE TITLE
Undefined references

### ISSUE THREAD

**Issue by ziyuang** [milakov/nnForge#17]
When compiling, these errors occur:

    + cd ../..
    + cd examples
    + for i in './*'
    + '[' -d ./Example.mk ']'
    + for i in './*'
    + '[' -d ./gtsrb ']'
    + cd ./gtsrb
    +make
    g++ -DNNFORGE_CUDA_BACKEND_ENABLED -I../.. -I/usr/include -I/usr/local/cuda/include -I/usr/local/cudnn -I/usr/include -fopenmp -ffast-math -march=native  -mfpmath=sse -msse2  -O3 -std=c++11 -DNNFORGE_CPP11COMPILER   -c -o gtsrb.o gtsrb.cpp
    g++ -DNNFORGE_CUDA_BACKEND_ENABLED -I../.. -I/usr/include -I/usr/local/cuda/include -I/usr/local/cudnn -I/usr/include -fopenmp -ffast-math -march=native  -mfpmath=sse -msse2  -O3 -std=c++11 -DNNFORGE_CPP11COMPILER   -c -o gtsrb_toolset.o gtsrb_toolset.cpp
    g++ -o ../../bin/gtsrb gtsrb.o gtsrb_toolset.o -lnnforge_cuda -lnnforge_plain -lnnforge -L../../lib -L/usr/lib -lboost_thread -lboost_regex -lboost_chrono -lboost_filesystem -lboost_program_options -lboost_random -lboost_system -lboost_date_time -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -L/usr/local/cudnn -lcudnn -lcurand -lcusparse -lcublas -lcudart -L/usr/lib -lopencv_highgui -lopencv_imgproc -lopencv_core -fopenmp
    gtsrb_toolset.o: In function `gtsrb_toolset::gtsrb_toolset(std::shared_ptr<nnforge::factory_generator>)':
    gtsrb_toolset.cpp:(.text+0x13db): undefined reference to `nnforge::neural_network_toolset::neural_network_toolset(std::shared_ptr<nnforge::factory_generator>)'
    gtsrb_toolset.o: In function `gtsrb_toolset::get_schema() const':
    gtsrb_toolset.cpp:(.text+0x159c): undefined reference to `nnforge::network_schema::add_layer(std::shared_ptr<nnforge::layer const>)'
    gtsrb_toolset.cpp:(.text+0x16d1): undefined reference to `nnforge::network_schema::add_layer(std::shared_ptr<nnforge::layer const>)'
    gtsrb_toolset.cpp:(.text+0x1738): undefined reference to `nnforge::network_schema::add_layer(std::shared_ptr<nnforge::layer const>)'
    gtsrb_toolset.cpp:(.text+0x177b): undefined reference to `nnforge::network_schema::add_layer(std::shared_ptr<nnforge::layer const>)'
    gtsrb_toolset.cpp:(.text+0x1845): undefined reference to `nnforge::network_schema::add_layer(std::shared_ptr<nnforge::layer const>)'
    gtsrb_toolset.o:gtsrb_toolset.cpp:(.text+0x1974): more undefined references to `nnforge::network_schema::add_layer(std::shared_ptr<nnforge::layer const>)' follow
    gtsrb_toolset.o: In function `gtsrb_toolset::prepare_training_data()':
    gtsrb_toolset.cpp:(.text+0x2f7f): undefined reference to `nnforge::supervised_data_stream_writer::supervised_data_stream_writer(std::shared_ptr<std::ostream>, nnforge::layer_configuration_specific const&, nnforge::layer_configuration_specific const&, nnforge::neuron_data_type::input_type)'
    gtsrb_toolset.cpp:(.text+0x3bb1): undefined reference to `nnforge::supervised_data_stream_writer::supervised_data_stream_writer(std::shared_ptr<std::ostream>, nnforge::layer_configuration_specific const&, nnforge::layer_configuration_specific const&, nnforge::neuron_data_type::input_type)'
    gtsrb_toolset.o:(.rodata._ZTV13gtsrb_toolset[_ZTV13gtsrb_toolset]+0x90): undefined reference to `nnforge::neural_network_toolset::get_validators_for_training(std::shared_ptr<nnforge::network_schema>)'
    gtsrb_toolset.o:(.rodata._ZTV13gtsrb_toolset[_ZTV13gtsrb_toolset]+0xb0): undefined reference to `nnforge::neural_network_toolset::run_test_with_unsupervised_data(std::vector<std::shared_ptr<nnforge::output_neuron_value_set>, std::allocator<std::shared_ptr<nnforge::output_neuron_value_set> > >&)'
    gtsrb_toolset.o:(.rodata._ZTV13gtsrb_toolset[_ZTV13gtsrb_toolset]+0x110): undefined reference to `nnforge::neural_network_toolset::get_samples_for_snapshot(std::shared_ptr<nnforge::network_data>, std::shared_ptr<nnforge::unsupervised_data_reader>, unsigned int)'
    collect2: error: ld returned 1 exit status
    make: *** [../../bin/gtsrb] Error 1
    

Also,

    + cd ..
    + for i in './*'
    + '[' -d ./image_classifier_demo ']'
    + cd ./image_classifier_demo
    + make
    g++ -o ../../bin/image_classifier_demo image_classifier_demo.o image_classifier_demo_toolset.o -lnnforge_cuda -lnnforge_plain -lnnforge -L../../lib -L/usr/lib -lboost_thread -lboost_regex -lboost_chrono -lboost_filesystem -lboost_program_options -lboost_random -lboost_system -lboost_date_time -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -L/usr/local/cudnn -lcudnn -lcurand -lcusparse -lcublas -lcudart -L/usr/lib -lopencv_highgui -lopencv_imgproc -lopencv_core -fopenmp
    image_classifier_demo_toolset.o:(.rodata._ZTV29image_classifier_demo_toolset[_ZTV29image_classifier_demo_toolset]+0x68): undefined reference to `nnforge::neural_network_toolset::get_dropout_rate_map() const'
    image_classifier_demo_toolset.o:(.rodata._ZTV29image_classifier_demo_toolset[_ZTV29image_classifier_demo_toolset]+0x140): undefined reference to `nnforge::neural_network_toolset::get_initial_data_reader_for_training() const'
    collect2: error: ld returned 1 exit status
    make: *** [../../bin/image_classifier_demo] Error 1

**Comment by milakov** [comment]
Please rebuild from scratch:
<pre>./make_all.sh clean
./make_all.sh</pre>

**Comment by ziyuang** [comment]
Got some new errors from ac8cd695 with CUDA 6.5 and cudnn v2 rc3 (have done `make_all.sh clean`)

    + cd plain
    + make
    ...
    dropout_layer_updater_plain.o dropout_layer_updater_plain.cpp
    dropout_layer_updater_plain.cpp: In member function "virtual void nnforge::plain::dropout_layer_updater_plain::test(nnforge::plain::const_additional_buffer_smart_ptr, nnforge::plain::additional_buffer_smart_ptr, std::vector<std::shared_ptr<std::vector<float> > >&, nnforge::plain::plain_running_configuration_const_smart_ptr, nnforge::const_layer_smart_ptr, nnforge::const_layer_data_smart_ptr, nnforge::const_layer_data_custom_smart_ptr, const nnforge::layer_configuration_specific&, const nnforge::layer_configuration_specific&, unsigned int, unsigned int, bool) const":
    dropout_layer_updater_plain.cpp:60:140: error: "memcpy" was not declared in this scope
         memcpy(&(output_buffer->at(0)), &(input_buffer->at(0)), input_configuration_specific.get_neuron_count() * updater_count * sizeof(float));
                                                                                                                                                ^
    make: *** [dropout_layer_updater_plain.o] Error 1
    
    ...
    
    + cd ../cuda
    + make
    g++ -I/usr/include -I/usr/local/cuda/include -I/usr/local/cudnn -I/usr/include -ffast-math -march=native  -mfpmath=sse -msse2  -O3 -std=c++11 -DNNFORGE_CPP11COMPILER   -c -o unsupervised_data_reader_async_helper.o unsupervised_data_reader_async_helper.cpp
    nvcc -c absolute_layer_tester_cuda.cu -use_fast_math -DBOOST_NOINLINE='__attribute__ ((noinline))' -O3 -Xcompiler="-I/usr/include -I/usr/local/cuda/include -I/usr/local/cudnn -I/usr/include -ffast-math -march=native  -mfpmath=sse -msse2  -O3" -DNNFORGE_CPP11COMPILER -std=c++11 -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=\"sm_35,compute_35\" -o absolute_layer_tester_cuda.o
    /usr/lib/gcc/x86_64-linux-gnu/4.8/include/wmmintrin.h(45): error: identifier "__builtin_ia32_aesdec128" is undefined
    ...(there are a lot of them)
    Error limit reached.
    100 errors detected in the compilation of "/tmp/tmpxft_00007dee_00000000-9_absolute_layer_tester_cuda.compute_35.cpp1.ii".
    Compilation terminated.
    make: *** [absolute_layer_tester_cuda.o] Error 4
    
    ...
    
    + cd ./gtsrb
    + make
    g++ -DNNFORGE_CUDA_BACKEND_ENABLED -I../.. -I/usr/include -I/usr/local/cuda/include -I/usr/local/cudnn -I/usr/include -fopenmp -ffast-math -march=native  -mfpmath=sse -msse2  -O3 -std=c++11 -DNNFORGE_CPP11COMPILER   -c -o gtsrb.o gtsrb.cpp
    g++ -DNNFORGE_CUDA_BACKEND_ENABLED -I../.. -I/usr/include -I/usr/local/cuda/include -I/usr/local/cudnn -I/usr/include -fopenmp -ffast-math -march=native  -mfpmath=sse -msse2  -O3 -std=c++11 -DNNFORGE_CPP11COMPILER   -c -o gtsrb_toolset.o gtsrb_toolset.cpp
    make: *** No rule to make target `-lnnforge_cuda', needed by `../../bin/gtsrb'.  Stop.
    + cd ..
    + for i in './*'
    + '[' -d ./image_classifier_demo ']'
    + cd ./image_classifier_demo
    + make
    g++ -DNNFORGE_CUDA_BACKEND_ENABLED -I../.. -I/usr/include -I/usr/local/cuda/include -I/usr/local/cudnn -I/usr/include -fopenmp -ffast-math -march=native  -mfpmath=sse -msse2  -O3 -std=c++11 -DNNFORGE_CPP11COMPILER   -c -o image_classifier_demo.o image_classifier_demo.cpp
    g++ -DNNFORGE_CUDA_BACKEND_ENABLED -I../.. -I/usr/include -I/usr/local/cuda/include -I/usr/local/cudnn -I/usr/include -fopenmp -ffast-math -march=native  -mfpmath=sse -msse2  -O3 -std=c++11 -DNNFORGE_CPP11COMPILER   -c -o image_classifier_demo_toolset.o image_classifier_demo_toolset.cpp
    make: *** No rule to make target `-lnnforge_cuda', needed by `../../bin/image_classifier_demo'.  Stop.

**Comment by milakov** [comment]
Regarding error when building cuda backend, try setting "CPP_HW_ARCHITECTURE=-march=corei7" in Settings.mk

**Comment by ziyuang** [comment]
Yes, it works.
