### ISSUE TITLE
nnForge train/test with imagenet dataset

### ISSUE THREAD

**Issue by anshumang** [milakov/nnForge#23]
@milakov I am curious about the effort required to do this.
Sorry for creating an issue as this is a mailing-list question.

**Comment by milakov** [comment]
It is doable. Actually, I have a project for training and validating model on ImageNet data. One would need to have all original training data at hand (150GB).

I am currently doing major refactoring for the nnForge framework, the plan is to publish ImageNet app when I finish this refactoring (might happen in ~2 months, cannot say for sure). But if you feel you ned it earlier I might consider publishing it for the current not yet refactored framework.

**Comment by anshumang** [comment]
I have downloaded the train and val data. Yes, it would be great if you could publish it soon.

**Comment by milakov** [comment]
Try it.

**Comment by anshumang** [comment]
It seems I need to rearrange the *.JPEG files under train/ directory. I have all the *.JPEG files extracted to the same parent directory. Instead, I should have nXXXX_YYYY.JPEG under directory nXXXX/ and so on. Keep you posted.

**Comment by anshumang** [comment]
Also, will I need a shell script to do what examples/imagenet/misc_files/generate_cls_class_info.m does?

**Comment by milakov** [comment]
You need Matlab or Octave, and also DevKit from ImageNet

**Comment by anshumang** [comment]
@milakov Is the meta_clsloc.mat supposed to be in the repo? I couldn't find it.

**Comment by milakov** [comment]
No, it is part of DevKit available at the same location you downloaded training and validating data.

**Comment by anshumang** [comment]
Got it, thanks !

**Comment by anshumang** [comment]
It works, thanks a ton :+1:

**Comment by anshumang** [comment]
Can this run without cudnn? I am looking to instrument some of the long running kernels but for that I need the kernel source.

**Comment by milakov** [comment]
Unfortunately no, cuDNN is a must.

**Comment by anshumang** [comment]
Is it possible to adapt v1.1.11 with imagenet application in current master to use the nnforge convolution kernels?

**Comment by milakov** [comment]
If you need to replace con layer only then you can do it with head of the master branch. Modifiy files nnforge/cuda/convolution_layer_testing_schema.cpp and nnforge/cuda/convolution_layer_updater_schema.cpp, replace 2 with 0 in "else if (input_configuration_specific.dimension_sizes.size() <= 2)"

**Comment by anshumang** [comment]
Getting the following exception with the above changes -

Exception caught: No CUDA updater for the convolutional layer of 2 dimensions for Kepler and above architectures

**Comment by anshumang** [comment]
:+1: 

By adding the lines,
case 2: 
           res = layer_updater_cuda_smart_ptr(new convolution_layer_updater_cuda_kepler<2>());
           break;
in nnforge/cuda/convolution_layer_updater_schema_helper_cuda_kepler.cu, 
the above exception is fixed.

**Comment by milakov** [comment]
Super!
