### ISSUE TITLE
FeedForward example

### ISSUE THREAD

**Issue by alexge233** [milakov/nnForge#24]
Hello,

I built the lib and went through the examples, and I was wondering if it would be too much to ask for a simple Feedforward example.

Many thanks,
A.

**Comment by milakov** [comment]
Hi Alex,

Sorry for the late answer, I am on vacation right now. Check imagenet_demo
example for online inference code. I am currently refactoring the
framework, will need to finish it first.

Max.
 23 июня 2015 г. 3:08 пользователь "Alex" <notifications@github.com>
написал:
